[package]
name = "lhef"
version = "0.1.0"
authors = ["Andreas Maier <andreas.maier@durham.ac.uk>"]
readme = "Readme.md"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
flate2 = "1.0"
