pub const LHEF_TAG_OPEN: &'static str = "<LesHouchesEvents version=";
pub const COMMENT_START: &'static str = "<!--";
pub const COMMENT_END: &'static str = "-->";
pub const HEADER_START: &'static str = "<header";
pub const HEADER_END: &'static str = "</header>";
pub const INIT_START: &'static str = "<init";
pub const INIT_END: &'static str = "</init>";
pub const EVENT_START: &'static str = "<event";
pub const EVENT_END: &'static str = "</event>";
pub const LHEF_LAST_LINE: &'static str = "</LesHouchesEvents>";
